language: node_js
node_js:
  - '11.10.1'

env:
  global:
    - CC_TEST_REPORTER_ID=6976ab254fd2c28761a002a7d1e68d34d56aad5f826f22bcb1316c2321bbdbb8

services:
  - postgresql

install:
  - npm install
  - npm install sequelize-cli


before_script:
  - psql -c 'create database stock_management_test;' -U postgres
  - curl -L
    https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - export DATABASE_URL_TEST='postgres://postgres:''@localhost:5432/stock_management_test'

script:
  - npm run db:reset:migrate:seed:test
  - npm run build

after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT